[package]
name = "mdbook-pagebreaks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["cargo", "wrap_help"] }
mdbook = "0.4.40"
semver = "1.0.23"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
