[book]
authors = ["Kylee Tilley"]
language = "en"
multilingual = false
src = "src"
title = "The Testing Book"

[preprocessor.embedify]
footer.enable = true
footer.message = "WIP • Copyright © 2024 [Kylee Tilley](https://github.com/testingrequired)"
scroll-to-top.enable = true

[preprocessor.mermaid]
[preprocessor.pagebreaks]

[output.html]
additional-js = ["node_modules/mermaid/dist/mermaid.min.js", "mermaid-init.js"]
additional-css = ["pagebreaks.css"]

[output.epub]
