default:
    @just --list

install:
    npm ci
    cd .. && ./scripts/install-mdbook-plugins.sh

# Build the project
build:
    mdbook build

# Clean the project
clean:
    mdbook clean

watch:
    mdbook serve --open
