name: E2E Test

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "./e2e/.nvmrc"
      - name: Install dependencies
        run: cd e2e && npm ci
      - name: Install Playwright Browsers
        run: cd e2e && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd e2e && npm test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
