name: Publish Site

permissions: write-all

on:
  push:
    paths:
      - "site/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "18.19.1"

      - name: Build site
        run: cd site && npm run build

      - name: Deploy site to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./
          publish_dir: ./site/dist
