name: Publish

permissions:
  pages: write
  contents: write

on:
  push:
    paths:
      - "site/**"
      - "book/**"
      - "scripts/**"
      - ".github/workflows/publish.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/setup-node@v4
        with:
          node-version-file: "./site/.nvmrc"

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup mdbook binary
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Restore cargo cache
        id: cache-cargo-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('./scripts/install-mdbook-plugins.sh') }}
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/

      - name: Install depdendencies
        run: just install

      - name: Save cargo cache
        id: cache-cargo-save
        uses: "actions/cache/save@v4"
        if: always() && steps.cache-cargo-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./scripts/install-mdbook-plugins.sh') }}

      - name: Build
        run: ./scripts/build.sh --base=/the-testing-book/
        env:
          MDBOOK_output__html__site_url: "/book/"

      - name: Test
        run: just test

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          destination_dir: ./
          publish_dir: ./dist/html

      - name: Upload html
        uses: actions/upload-artifact@v4
        with:
          name: the-testing-book-html
          path: dist/html/book

      - name: Upload epub
        uses: actions/upload-artifact@v4
        with:
          name: the-testing-book-epub
          path: dist/epub
