name: Publish

permissions: write-all

on:
  push:
    paths:
      - "site/**"
      - "book/**"
      - "scripts/**"
      - ".github/workflows/publish.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup mdbook binary
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - uses: actions/setup-node@v4
        with:
          node-version-file: "./site/.nvmrc"

      - name: Install site dependencies
        run: cd site && npm ci

      - name: Build
        run: ./scripts/build.sh --base=/the-testing-book/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ./
          publish_dir: ./dist
